environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor.monacelli@streambox.com

on_finish:
#- sh: export APPVEYOR_SSH_BLOCK=true
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

image: Ubuntu2004
install:
- sudo apt-get -qqy update
- sudo apt-get -qqy install python3-pip python3.8-venv
- python3 -mvenv .venv
- source .venv/bin/activate && pip install --quiet tox-docker
test_script:
- sudo mkdir -p /my/own/datadir && chmdo -R a+rwx /my/own/datadir
- source .venv/bin/activate && tox
build: off
